//! sme-gemm vs ONNX Runtime CPU / `XNNPACK` / `CoreML` execution providers, on a
//! single-`MatMul` ONNX graph (generated by `models/gen_onnx.py`). Same data,
//! same best-of-N. Shows whether the SME path beats ORT's strongest Apple EPs.
//!   uv run `models/gen_onnx.py`          # once, to build the .onnx models
//!   cargo run --release --features ort --example `vs_ort`

use std::time::Instant;

use half::f16;
use ort::ep::{CPU, CoreML, ExecutionProviderDispatch, XNNPACK};
use ort::session::Session;
use ort::value::Tensor;
use sme_gemm::{Accum, matmul_f16, matmul_f32};

/// Best-of-N across every backend, INTERLEAVED: one timed round of each per
/// pass. Run to completion in turn instead, whichever goes first pays the clock
/// ramp and each one inherits the heat of all the ones before it -- with four
/// backends that bias is larger than the gaps being measured.
fn best_interleaved(big: bool, fs: &mut [&mut dyn FnMut()]) -> Vec<f64> {
    for f in fs.iter_mut() {
        for _ in 0..3 {
            f();
        }
    }
    let iters = if big { 4 } else { 30 };
    let mut best = vec![f64::INFINITY; fs.len()];
    for _ in 0..10 {
        for (i, f) in fs.iter_mut().enumerate() {
            let t = Instant::now();
            for _ in 0..iters {
                f();
            }
            best[i] = best[i].min(t.elapsed().as_secs_f64() / f64::from(iters));
        }
    }
    best
}

fn session(model: &str, eps: Vec<ExecutionProviderDispatch>) -> Session {
    Session::builder()
        .expect("ort call failed")
        .with_execution_providers(eps)
        .expect("ort call failed")
        .commit_from_file(model)
        .expect("ort call failed")
}

fn main() {
    let dir = env!("CARGO_MANIFEST_DIR");
    let sizes: &[(usize, usize, usize)] = &[
        (256, 256, 256),
        (512, 512, 512),
        (1024, 1024, 1024),
        (2048, 2048, 2048),
        (4096, 512, 512),
    ];

    // f32 ---------------------------------------------------------------------
    let model = format!("{dir}/models/gemm_f32.onnx");
    let mut cpu = session(&model, vec![CPU::default().build()]);
    let mut xnn = session(&model, vec![XNNPACK::default().build()]);
    let mut coreml = session(&model, vec![CoreML::default().build()]);
    println!("== f32: sme-gemm vs ONNX Runtime (TF/s) ==");
    println!(
        "  {:>16}  {:>7}  {:>7}  {:>7}  {:>7}",
        "shape", "sme", "ort-cpu", "xnnpack", "coreml"
    );
    for &(m, n, k) in sizes {
        let big = m * n * k > 64 << 20;
        let flop = 2.0 * (m * n * k) as f64;
        let av = vec![0.02f32; m * k];
        let bv = vec![0.03f32; k * n];
        let mut c = vec![0.0f32; m * n];
        let tf = |s: f64| flop / s / 1e12;
        let a = Tensor::from_array(([m, k], av.clone())).expect("ort call failed");
        let b = Tensor::from_array(([k, n], bv.clone())).expect("ort call failed");
        let mut f_sme = || matmul_f32(&av, &bv, &mut c, m, n, k);
        let mut f_cpu = || {
            cpu.run(ort::inputs!["A" => &a, "B" => &b])
                .expect("ort call failed");
        };
        let mut f_xnn = || {
            xnn.run(ort::inputs!["A" => &a, "B" => &b])
                .expect("ort call failed");
        };
        let mut f_ml = || {
            coreml
                .run(ort::inputs!["A" => &a, "B" => &b])
                .expect("ort call failed");
        };
        let s = best_interleaved(big, &mut [&mut f_sme, &mut f_cpu, &mut f_xnn, &mut f_ml]);
        let (sme, rc, rx, rm) = (tf(s[0]), tf(s[1]), tf(s[2]), tf(s[3]));
        println!("  {m:>5}x{n:<4}x{k:<4}  {sme:>7.2}  {rc:>7.2}  {rx:>7.2}  {rm:>7.2}");
    }

    // f16 ---------------------------------------------------------------------
    let model = format!("{dir}/models/gemm_f16.onnx");
    let mut cpu = session(&model, vec![CPU::default().build()]);
    let mut coreml = session(&model, vec![CoreML::default().build()]);
    println!("\n== f16: sme-gemm vs ONNX Runtime (TF/s) ==");
    println!(
        "  {:>16}  {:>7}  {:>7}  {:>7}",
        "shape", "sme", "ort-cpu", "coreml"
    );
    for &(m, n, k) in sizes {
        let big = m * n * k > 64 << 20;
        let flop = 2.0 * (m * n * k) as f64;
        let av = vec![f16::from_f32(0.02); m * k];
        let bv = vec![f16::from_f32(0.03); k * n];
        let mut c = vec![f16::ZERO; m * n];
        let tf = |s: f64| flop / s / 1e12;
        let a = Tensor::from_array(([m, k], av.clone())).expect("ort call failed");
        let b = Tensor::from_array(([k, n], bv.clone())).expect("ort call failed");
        let mut f_sme = || {
            matmul_f16(&av, &bv, &mut c, m, n, k, Accum::F16);
        };
        let mut f_cpu = || {
            cpu.run(ort::inputs!["A" => &a, "B" => &b])
                .expect("ort call failed");
        };
        let mut f_ml = || {
            coreml
                .run(ort::inputs!["A" => &a, "B" => &b])
                .expect("ort call failed");
        };
        let s = best_interleaved(big, &mut [&mut f_sme, &mut f_cpu, &mut f_ml]);
        let (sme, rc, rm) = (tf(s[0]), tf(s[1]), tf(s[2]));
        println!("  {m:>5}x{n:<4}x{k:<4}  {sme:>7.2}  {rc:>7.2}  {rm:>7.2}");
    }
}
